### ISSUE TITLE
Лучше опираться не предыдущее значение

### ISSUE THREAD

**Issue by coursar** [Lapeno23/SportmasterMaven#7]
https://github.com/Lapeno23/SportmasterMaven/blob/1c006c56cc064a59831d1fddd6e5e8b65e11bf43/src/main/java/ru/itpark/BonusService.java#L12-L13

```java
 int maxHistoryTotalAmountForSilver = 150_000; 
 int minPurchaseAmountForGold = maxHistoryTotalAmountForSilver + 1; 
```

**Comment by Lapeno23** [comment]
87262cb19ce103062dd06db49e5d57bb8a6a4d60
